# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2019.2.2\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2019.2.2\bin\cmake\win\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\kmb99\CLionProjects\OMP-tasks(OMP)

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\kmb99\CLionProjects\OMP-tasks(OMP)

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Program Files\JetBrains\CLion 2019.2.2\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\JetBrains\CLion 2019.2.2\bin\cmake\win\bin\cmake.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\kmb99\CLionProjects\OMP-tasks(OMP)\CMakeFiles C:\Users\kmb99\CLionProjects\OMP-tasks(OMP)\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\kmb99\CLionProjects\OMP-tasks(OMP)\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OMP-tasks

# Build rule for target.
OMP-tasks: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 OMP-tasks
.PHONY : OMP-tasks

# fast build rule for target.
OMP-tasks/fast:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/build
.PHONY : OMP-tasks/fast

mpi/launcherMPI.obj: mpi/launcherMPI.cpp.obj

.PHONY : mpi/launcherMPI.obj

# target to build an object file
mpi/launcherMPI.cpp.obj:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/launcherMPI.cpp.obj
.PHONY : mpi/launcherMPI.cpp.obj

mpi/launcherMPI.i: mpi/launcherMPI.cpp.i

.PHONY : mpi/launcherMPI.i

# target to preprocess a source file
mpi/launcherMPI.cpp.i:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/launcherMPI.cpp.i
.PHONY : mpi/launcherMPI.cpp.i

mpi/launcherMPI.s: mpi/launcherMPI.cpp.s

.PHONY : mpi/launcherMPI.s

# target to generate assembly for a file
mpi/launcherMPI.cpp.s:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/launcherMPI.cpp.s
.PHONY : mpi/launcherMPI.cpp.s

mpi/taskMPI1.obj: mpi/taskMPI1.cpp.obj

.PHONY : mpi/taskMPI1.obj

# target to build an object file
mpi/taskMPI1.cpp.obj:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI1.cpp.obj
.PHONY : mpi/taskMPI1.cpp.obj

mpi/taskMPI1.i: mpi/taskMPI1.cpp.i

.PHONY : mpi/taskMPI1.i

# target to preprocess a source file
mpi/taskMPI1.cpp.i:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI1.cpp.i
.PHONY : mpi/taskMPI1.cpp.i

mpi/taskMPI1.s: mpi/taskMPI1.cpp.s

.PHONY : mpi/taskMPI1.s

# target to generate assembly for a file
mpi/taskMPI1.cpp.s:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI1.cpp.s
.PHONY : mpi/taskMPI1.cpp.s

mpi/taskMPI10.obj: mpi/taskMPI10.cpp.obj

.PHONY : mpi/taskMPI10.obj

# target to build an object file
mpi/taskMPI10.cpp.obj:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI10.cpp.obj
.PHONY : mpi/taskMPI10.cpp.obj

mpi/taskMPI10.i: mpi/taskMPI10.cpp.i

.PHONY : mpi/taskMPI10.i

# target to preprocess a source file
mpi/taskMPI10.cpp.i:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI10.cpp.i
.PHONY : mpi/taskMPI10.cpp.i

mpi/taskMPI10.s: mpi/taskMPI10.cpp.s

.PHONY : mpi/taskMPI10.s

# target to generate assembly for a file
mpi/taskMPI10.cpp.s:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI10.cpp.s
.PHONY : mpi/taskMPI10.cpp.s

mpi/taskMPI11.obj: mpi/taskMPI11.cpp.obj

.PHONY : mpi/taskMPI11.obj

# target to build an object file
mpi/taskMPI11.cpp.obj:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI11.cpp.obj
.PHONY : mpi/taskMPI11.cpp.obj

mpi/taskMPI11.i: mpi/taskMPI11.cpp.i

.PHONY : mpi/taskMPI11.i

# target to preprocess a source file
mpi/taskMPI11.cpp.i:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI11.cpp.i
.PHONY : mpi/taskMPI11.cpp.i

mpi/taskMPI11.s: mpi/taskMPI11.cpp.s

.PHONY : mpi/taskMPI11.s

# target to generate assembly for a file
mpi/taskMPI11.cpp.s:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI11.cpp.s
.PHONY : mpi/taskMPI11.cpp.s

mpi/taskMPI2.obj: mpi/taskMPI2.cpp.obj

.PHONY : mpi/taskMPI2.obj

# target to build an object file
mpi/taskMPI2.cpp.obj:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI2.cpp.obj
.PHONY : mpi/taskMPI2.cpp.obj

mpi/taskMPI2.i: mpi/taskMPI2.cpp.i

.PHONY : mpi/taskMPI2.i

# target to preprocess a source file
mpi/taskMPI2.cpp.i:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI2.cpp.i
.PHONY : mpi/taskMPI2.cpp.i

mpi/taskMPI2.s: mpi/taskMPI2.cpp.s

.PHONY : mpi/taskMPI2.s

# target to generate assembly for a file
mpi/taskMPI2.cpp.s:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI2.cpp.s
.PHONY : mpi/taskMPI2.cpp.s

mpi/taskMPI3.obj: mpi/taskMPI3.cpp.obj

.PHONY : mpi/taskMPI3.obj

# target to build an object file
mpi/taskMPI3.cpp.obj:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI3.cpp.obj
.PHONY : mpi/taskMPI3.cpp.obj

mpi/taskMPI3.i: mpi/taskMPI3.cpp.i

.PHONY : mpi/taskMPI3.i

# target to preprocess a source file
mpi/taskMPI3.cpp.i:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI3.cpp.i
.PHONY : mpi/taskMPI3.cpp.i

mpi/taskMPI3.s: mpi/taskMPI3.cpp.s

.PHONY : mpi/taskMPI3.s

# target to generate assembly for a file
mpi/taskMPI3.cpp.s:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI3.cpp.s
.PHONY : mpi/taskMPI3.cpp.s

mpi/taskMPI4.obj: mpi/taskMPI4.cpp.obj

.PHONY : mpi/taskMPI4.obj

# target to build an object file
mpi/taskMPI4.cpp.obj:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI4.cpp.obj
.PHONY : mpi/taskMPI4.cpp.obj

mpi/taskMPI4.i: mpi/taskMPI4.cpp.i

.PHONY : mpi/taskMPI4.i

# target to preprocess a source file
mpi/taskMPI4.cpp.i:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI4.cpp.i
.PHONY : mpi/taskMPI4.cpp.i

mpi/taskMPI4.s: mpi/taskMPI4.cpp.s

.PHONY : mpi/taskMPI4.s

# target to generate assembly for a file
mpi/taskMPI4.cpp.s:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI4.cpp.s
.PHONY : mpi/taskMPI4.cpp.s

mpi/taskMPI5.obj: mpi/taskMPI5.cpp.obj

.PHONY : mpi/taskMPI5.obj

# target to build an object file
mpi/taskMPI5.cpp.obj:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI5.cpp.obj
.PHONY : mpi/taskMPI5.cpp.obj

mpi/taskMPI5.i: mpi/taskMPI5.cpp.i

.PHONY : mpi/taskMPI5.i

# target to preprocess a source file
mpi/taskMPI5.cpp.i:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI5.cpp.i
.PHONY : mpi/taskMPI5.cpp.i

mpi/taskMPI5.s: mpi/taskMPI5.cpp.s

.PHONY : mpi/taskMPI5.s

# target to generate assembly for a file
mpi/taskMPI5.cpp.s:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI5.cpp.s
.PHONY : mpi/taskMPI5.cpp.s

mpi/taskMPI6.obj: mpi/taskMPI6.cpp.obj

.PHONY : mpi/taskMPI6.obj

# target to build an object file
mpi/taskMPI6.cpp.obj:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI6.cpp.obj
.PHONY : mpi/taskMPI6.cpp.obj

mpi/taskMPI6.i: mpi/taskMPI6.cpp.i

.PHONY : mpi/taskMPI6.i

# target to preprocess a source file
mpi/taskMPI6.cpp.i:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI6.cpp.i
.PHONY : mpi/taskMPI6.cpp.i

mpi/taskMPI6.s: mpi/taskMPI6.cpp.s

.PHONY : mpi/taskMPI6.s

# target to generate assembly for a file
mpi/taskMPI6.cpp.s:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI6.cpp.s
.PHONY : mpi/taskMPI6.cpp.s

mpi/taskMPI7.obj: mpi/taskMPI7.cpp.obj

.PHONY : mpi/taskMPI7.obj

# target to build an object file
mpi/taskMPI7.cpp.obj:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI7.cpp.obj
.PHONY : mpi/taskMPI7.cpp.obj

mpi/taskMPI7.i: mpi/taskMPI7.cpp.i

.PHONY : mpi/taskMPI7.i

# target to preprocess a source file
mpi/taskMPI7.cpp.i:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI7.cpp.i
.PHONY : mpi/taskMPI7.cpp.i

mpi/taskMPI7.s: mpi/taskMPI7.cpp.s

.PHONY : mpi/taskMPI7.s

# target to generate assembly for a file
mpi/taskMPI7.cpp.s:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI7.cpp.s
.PHONY : mpi/taskMPI7.cpp.s

mpi/taskMPI8.obj: mpi/taskMPI8.cpp.obj

.PHONY : mpi/taskMPI8.obj

# target to build an object file
mpi/taskMPI8.cpp.obj:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI8.cpp.obj
.PHONY : mpi/taskMPI8.cpp.obj

mpi/taskMPI8.i: mpi/taskMPI8.cpp.i

.PHONY : mpi/taskMPI8.i

# target to preprocess a source file
mpi/taskMPI8.cpp.i:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI8.cpp.i
.PHONY : mpi/taskMPI8.cpp.i

mpi/taskMPI8.s: mpi/taskMPI8.cpp.s

.PHONY : mpi/taskMPI8.s

# target to generate assembly for a file
mpi/taskMPI8.cpp.s:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI8.cpp.s
.PHONY : mpi/taskMPI8.cpp.s

mpi/taskMPI9.obj: mpi/taskMPI9.cpp.obj

.PHONY : mpi/taskMPI9.obj

# target to build an object file
mpi/taskMPI9.cpp.obj:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI9.cpp.obj
.PHONY : mpi/taskMPI9.cpp.obj

mpi/taskMPI9.i: mpi/taskMPI9.cpp.i

.PHONY : mpi/taskMPI9.i

# target to preprocess a source file
mpi/taskMPI9.cpp.i:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI9.cpp.i
.PHONY : mpi/taskMPI9.cpp.i

mpi/taskMPI9.s: mpi/taskMPI9.cpp.s

.PHONY : mpi/taskMPI9.s

# target to generate assembly for a file
mpi/taskMPI9.cpp.s:
	$(MAKE) -f CMakeFiles\OMP-tasks.dir\build.make CMakeFiles/OMP-tasks.dir/mpi/taskMPI9.cpp.s
.PHONY : mpi/taskMPI9.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... OMP-tasks
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... mpi/launcherMPI.obj
	@echo ... mpi/launcherMPI.i
	@echo ... mpi/launcherMPI.s
	@echo ... mpi/taskMPI1.obj
	@echo ... mpi/taskMPI1.i
	@echo ... mpi/taskMPI1.s
	@echo ... mpi/taskMPI10.obj
	@echo ... mpi/taskMPI10.i
	@echo ... mpi/taskMPI10.s
	@echo ... mpi/taskMPI11.obj
	@echo ... mpi/taskMPI11.i
	@echo ... mpi/taskMPI11.s
	@echo ... mpi/taskMPI2.obj
	@echo ... mpi/taskMPI2.i
	@echo ... mpi/taskMPI2.s
	@echo ... mpi/taskMPI3.obj
	@echo ... mpi/taskMPI3.i
	@echo ... mpi/taskMPI3.s
	@echo ... mpi/taskMPI4.obj
	@echo ... mpi/taskMPI4.i
	@echo ... mpi/taskMPI4.s
	@echo ... mpi/taskMPI5.obj
	@echo ... mpi/taskMPI5.i
	@echo ... mpi/taskMPI5.s
	@echo ... mpi/taskMPI6.obj
	@echo ... mpi/taskMPI6.i
	@echo ... mpi/taskMPI6.s
	@echo ... mpi/taskMPI7.obj
	@echo ... mpi/taskMPI7.i
	@echo ... mpi/taskMPI7.s
	@echo ... mpi/taskMPI8.obj
	@echo ... mpi/taskMPI8.i
	@echo ... mpi/taskMPI8.s
	@echo ... mpi/taskMPI9.obj
	@echo ... mpi/taskMPI9.i
	@echo ... mpi/taskMPI9.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

